// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDSy-O2YdZtE1fsIV_0HdennY_yZVQSQ',
    appId: '1:777379347323:web:364b336eb4c26da1ba9bde',
    messagingSenderId: '777379347323',
    projectId: 'lzprices',
    authDomain: 'lzprices.firebaseapp.com',
    storageBucket: 'lzprices.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_QCXK3G75vMO_rVu98u5A5OLlLEOfJQ',
    appId: '1:777379347323:android:a1e28c9075f78fb7ba9bde',
    messagingSenderId: '777379347323',
    projectId: 'lzprices',
    storageBucket: 'lzprices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZuou3S799-re7x3Rsvv-2Jc4shri34A',
    appId: '1:777379347323:ios:9dcd3bd70332ff6bba9bde',
    messagingSenderId: '777379347323',
    projectId: 'lzprices',
    storageBucket: 'lzprices.firebasestorage.app',
    iosBundleId: 'com.example.windowsGoogleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuZuou3S799-re7x3Rsvv-2Jc4shri34A',
    appId: '1:777379347323:ios:9dcd3bd70332ff6bba9bde',
    messagingSenderId: '777379347323',
    projectId: 'lzprices',
    storageBucket: 'lzprices.firebasestorage.app',
    iosBundleId: 'com.example.windowsGoogleSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMDSy-O2YdZtE1fsIV_0HdennY_yZVQSQ',
    appId: '1:777379347323:web:cc0b5ee952e506eaba9bde',
    messagingSenderId: '777379347323',
    projectId: 'lzprices',
    authDomain: 'lzprices.firebaseapp.com',
    storageBucket: 'lzprices.firebasestorage.app',
  );

}