// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFSTRsJfKOiObilNVbz1i3RLZkiZP6KQ',
    appId: '1:971891419951:web:c454d869fcae95d9418fda',
    messagingSenderId: '971891419951',
    projectId: 'windows--signin',
    authDomain: 'windows--signin.firebaseapp.com',
    storageBucket: 'windows--signin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAslpY5o5Eh7OO19qdiAIf210xHZat9Fc',
    appId: '1:971891419951:android:e0d79aa0dc2f624a418fda',
    messagingSenderId: '971891419951',
    projectId: 'windows--signin',
    storageBucket: 'windows--signin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6-xu0TUolnPK6CwsaT42faE9sSWSGYg',
    appId: '1:971891419951:ios:6bc844c1c6983f47418fda',
    messagingSenderId: '971891419951',
    projectId: 'windows--signin',
    storageBucket: 'windows--signin.firebasestorage.app',
    iosBundleId: 'com.example.windowsGoogleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6-xu0TUolnPK6CwsaT42faE9sSWSGYg',
    appId: '1:971891419951:ios:6bc844c1c6983f47418fda',
    messagingSenderId: '971891419951',
    projectId: 'windows--signin',
    storageBucket: 'windows--signin.firebasestorage.app',
    iosBundleId: 'com.example.windowsGoogleSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAFSTRsJfKOiObilNVbz1i3RLZkiZP6KQ',
    appId: '1:971891419951:web:cd0975b4bbc16387418fda',
    messagingSenderId: '971891419951',
    projectId: 'windows--signin',
    authDomain: 'windows--signin.firebaseapp.com',
    storageBucket: 'windows--signin.firebasestorage.app',
  );
}
